### ISSUE TITLE
Minor optimization for AdaTimeSpanReader

### ISSUE THREAD

**Issue by Joe4evr** [Emzi0767/Discord-ADA-Bot#1]
The [`reg` and `gps` variables](https://github.com/Emzi0767/Discord-ADA-Bot/blob/ada-4.0/Emzi0767.Ada/Commands/AdaTimeSpanReader.cs#L22-L23) can be lifted to static (readonly) fields to reduce allocating (and subsequently GC'ing) the same exact objects multiple times.

**Comment by Emzi0767** [comment]
Will do in the rewrite. Thanks for pointing this out.

**Comment by Emzi0767** [comment]
Implemented in 07dce30c7ea0c936b4ff22227fcb2c018f5ded60.
